name: flutter_redurx
version: 1.0.0+1
description: Flutter bindings for ReduRx (A thin layer of a Redux-based state manager on top of RxDart).

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dependency_overrides:
  redurx:
    git: https://github.com/developeranshul1986/ReduRx.git

dev_dependencies:
  flutter_test:
    sdk: flutter
